sudo: required

language: ruby

services:
  - docker

before_install:
  - docker build -t superphy/docker-flask-conda:latest .
  - docker run -d -p 127.0.0.1:80:4567 superphy/docker-flask-conda:latest
  - docker ps -a

install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push superphy/docker-flask-conda:latest
script:
  - curl http://localhost:4567
notifications:
  email: false
